# Generated by Django 3.0.8 on 2020-08-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('gym', 'Gym'), ('restaurant', 'Restaurant'), ('lodging', 'Hotel')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('gym', 'Gym'), ('restaurant', 'Restaurant'), ('lodging', 'Hotel')], default=None, max_length=10),
        ),
    ]
