# Generated by Django 3.1 on 2020-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='latitude',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='longitude',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
